# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c210e9a531a5c7e7fc8409950fafa7074470845db7d34d49a915d738b880a6a23d1f8ede216e69273ee6543e020ef7055b10b81a3e7bcac00212f5c5946ee83a

test:
  secret_key_base: b5fe01473aefd88455cd1948b7c3c193ebca1f03b45936d80a5da9bb10b4640a9989e81f02dfd3030225c404d0cfa6edc7c7971cfeeb1304cf3ea8b64534594b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
